[package]
authors = ["NVIDIA"]
category = "services"
changelog = "docs/CHANGELOG.md"
description = "Digital Bot Lab Asset Provider"
icon = "data/digitalbotlab.png"
keywords = ["asset", "provider", "sketchfab"]
preview_image = "data/preview.png"
readme = "docs/README.md"
repository = ""
title = "Asset Provider for Digital Bot Lab"
version = "1.0.10"

[dependencies]
"omni.services.browser.asset" = {}

[[python.module]]
name = "omni.kit.browser.asset_provider.sketchfab"

[settings]
exts."omni.asset_provider.digitalbotlab".enable = true
exts."omni.asset_provider.digitalbotlab".providerId = "Digital Bot Lab"
exts."omni.asset_provider.digitalbotlab".keepOriginalPageSize = true
exts."omni.asset_provider.digitalbotlab".maxCountPerPage = 24
exts."omni.asset_provider.digitalbotlab".minThumbnailSize = 256
exts."omni.asset_provider.digitalbotlab".searchUrl = "https://api.sketchfab.com/v3/search"
exts."omni.asset_provider.digitalbotlab".modelsUrl = "https://api.sketchfab.com/v3/models"
exts."omni.asset_provider.digitalbotlab".authorizeUrl = "https://sketchfab.com/oauth2/authorize/"
exts."omni.asset_provider.digitalbotlab".accessTokenUrl = "https://sketchfab.com/oauth2/token/"
exts."omni.asset_provider.digitalbotlab".clientId = "eQcrihd32CeYmF9evsYEGXZr8vynHA82DW7SzJw2"
exts."omni.asset_provider.digitalbotlab".clientSecret = ""

[[test]]
dependencies = ["omni.services.client", "omni.client"]
